basePath: /v3
definitions:
  model.APIData:
    properties:
      last_page:
        description: Last page of requested board
        type: integer
      posts:
        description: Data of board
        items:
          $ref: '#/definitions/model.Board'
        type: array
    type: object
  model.Article:
    properties:
      article_url:
        type: string
      content:
        type: string
      files:
        items:
          $ref: '#/definitions/model.Files'
        type: array
      id:
        type: string
      title:
        type: string
      write_date:
        type: string
      writer:
        type: string
    type: object
  model.Board:
    properties:
      id:
        type: string
      num:
        type: string
      read_count:
        type: integer
      title:
        type: string
      write_date:
        type: string
      writer:
        type: string
    type: object
  model.Files:
    properties:
      file_name:
        type: string
      file_url:
        type: string
    type: object
info:
  contact:
    email: kongwoojin03@gmail.com
    name: Developer
  description: This is unofficial version of KOREATECH board REST API
  title: KOREATECH board REST API
  version: "1.0"
paths:
  /arch/{board}:
    get:
      consumes:
      - application/json
      description: Get arch article list
      parameters:
      - description: name of the board
        in: path
        name: board
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.APIData'
        "404":
          description: Not Found
      summary: Get article list
      tags:
      - arch
  /article/arch:
    get:
      consumes:
      - application/json
      description: Get arch article by UUID
      parameters:
      - description: uuid of article
        in: query
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Article'
        "404":
          description: Not Found
      summary: Get article
      tags:
      - arch
  /article/cse:
    get:
      consumes:
      - application/json
      description: Get cse article by UUID
      parameters:
      - description: uuid of article
        in: query
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Article'
        "404":
          description: Not Found
      summary: Get article
      tags:
      - cse
  /article/dorm:
    get:
      consumes:
      - application/json
      description: Get dorm article by UUID
      parameters:
      - description: uuid of article
        in: query
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Article'
        "404":
          description: Not Found
      summary: Get article
      tags:
      - dorm
  /article/emc:
    get:
      consumes:
      - application/json
      description: Get emc article by UUID
      parameters:
      - description: uuid of article
        in: query
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Article'
        "404":
          description: Not Found
      summary: Get article
      tags:
      - emc
  /article/ide:
    get:
      consumes:
      - application/json
      description: Get ide article by UUID
      parameters:
      - description: uuid of article
        in: query
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Article'
        "404":
          description: Not Found
      summary: Get article
      tags:
      - ide
  /article/ite:
    get:
      consumes:
      - application/json
      description: Get ite article by UUID
      parameters:
      - description: uuid of article
        in: query
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Article'
        "404":
          description: Not Found
      summary: Get article
      tags:
      - ite
  /article/mechanical:
    get:
      consumes:
      - application/json
      description: Get mechanical article by UUID
      parameters:
      - description: uuid of article
        in: query
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Article'
        "404":
          description: Not Found
      summary: Get article
      tags:
      - mechanical
  /article/mechatronics:
    get:
      consumes:
      - application/json
      description: Get mechatronics article by UUID
      parameters:
      - description: uuid of article
        in: query
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Article'
        "404":
          description: Not Found
      summary: Get article
      tags:
      - mechatronics
  /article/school:
    get:
      consumes:
      - application/json
      description: Get school article by UUID
      parameters:
      - description: uuid of article
        in: query
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Article'
        "404":
          description: Not Found
      summary: Get article
      tags:
      - school
  /article/sim:
    get:
      consumes:
      - application/json
      description: Get sim article by UUID
      parameters:
      - description: uuid of article
        in: query
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Article'
        "404":
          description: Not Found
      summary: Get article
      tags:
      - sim
  /cse/{board}:
    get:
      consumes:
      - application/json
      description: Get cse article list
      parameters:
      - description: name of the board
        in: path
        name: board
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.APIData'
        "404":
          description: Not Found
      summary: Get article list
      tags:
      - cse
  /dorm/{board}:
    get:
      consumes:
      - application/json
      description: Get dorm article list
      parameters:
      - description: name of the board
        in: path
        name: board
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.APIData'
        "404":
          description: Not Found
      summary: Get article list
      tags:
      - dorm
  /emc/{board}:
    get:
      consumes:
      - application/json
      description: Get emc article list
      parameters:
      - description: name of the board
        in: path
        name: board
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.APIData'
        "404":
          description: Not Found
      summary: Get article list
      tags:
      - emc
  /ide/{board}:
    get:
      consumes:
      - application/json
      description: Get ide article list
      parameters:
      - description: name of the board
        in: path
        name: board
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.APIData'
        "404":
          description: Not Found
      summary: Get article list
      tags:
      - ide
  /ite/{board}:
    get:
      consumes:
      - application/json
      description: Get ite article list
      parameters:
      - description: name of the board
        in: path
        name: board
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.APIData'
        "404":
          description: Not Found
      summary: Get article list
      tags:
      - ite
  /mechanical/{board}:
    get:
      consumes:
      - application/json
      description: Get mechanical article list
      parameters:
      - description: name of the board
        in: path
        name: board
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.APIData'
        "404":
          description: Not Found
      summary: Get article list
      tags:
      - mechanical
  /mechatronics/{board}:
    get:
      consumes:
      - application/json
      description: Get mechatronics article list
      parameters:
      - description: name of the board
        in: path
        name: board
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.APIData'
        "404":
          description: Not Found
      summary: Get article list
      tags:
      - mechatronics
  /school/{board}:
    get:
      consumes:
      - application/json
      description: Get school article list
      parameters:
      - description: name of the board
        in: path
        name: board
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.APIData'
        "404":
          description: Not Found
      summary: Get article list
      tags:
      - school
  /sim/{board}:
    get:
      consumes:
      - application/json
      description: Get sim article list
      parameters:
      - description: name of the board
        in: path
        name: board
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.APIData'
        "404":
          description: Not Found
      summary: Get article list
      tags:
      - sim
swagger: "2.0"
